In [ ]:
# 4 input layers with 3 batches, 3 hidden layer 1, 3 output layers
import numpy as np

# input
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

# input and first hidden layer weights and biases
weights1 = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases1 = [2.0, 3.0, 0.5]

# hidden layer 1 and output layer weights and biases
weights2 = [[0.1, -0.14, 0.5],
           [-0.5, 0.12, -0.33],
           [-0.44, 0.73, -0.13]]
biases2 = [-1.0, 2.0, 0.5]

layer_outputs1 = np.dot(inputs, np.array(weights1).T) + biases1
print(layer_outputs1)
layer_outputs = np.dot(layer_outputs1, np.array(weights2).T) + biases2
print(layer_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
[[ 0.5031  -1.04185 -1.03875]
 [ 0.2434  -2.7332  -4.7633 ]
 [-0.99314  1.41254  0.64345]]
