Importance of keepdim in numpy.

In [2]:
import numpy as np
inputs = [[1,2,3], [4,5,6], [7,8,9]]

print(np.sum(inputs))

45


In [4]:
# row
print(np.sum(inputs, axis=0))
print(np.sum(inputs, axis=0).shape)

# column
print(np.sum(inputs, axis=1))
print(np.sum(inputs, axis=1).shape)

[12 15 18]
(3,)
[ 6 15 24]
(3,)


In [7]:
# keepdims preserves the dimensions of the original array
print(np.sum(inputs, axis=0, keepdims=True))
print(np.sum(inputs, axis=0, keepdims=True).shape)
print("\n")
print(np.sum(inputs, axis=1, keepdims=True))
print(np.sum(inputs, axis=1, keepdims=True).shape)

[[12 15 18]]
(1, 3)


[[ 6]
 [15]
 [24]]
(3, 1)


Print maximum value according to row or column.

In [10]:
print(np.max(inputs, axis=0))
print(np.max(inputs, axis=0).shape)
print(np.max(inputs, axis=1))
print(np.max(inputs, axis=1).shape)

[7 8 9]
(3,)
[3 6 9]
(3,)


In [11]:
print(np.max(inputs, axis=0, keepdims=True))
print(np.max(inputs, axis=0, keepdims=True).shape)
print("\n")
print(np.max(inputs, axis=1, keepdims=True))
print(np.max(inputs, axis=1, keepdims=True).shape)

[[7 8 9]]
(1, 3)


[[3]
 [6]
 [9]]
(3, 1)
