<h1>RELU activation</h1>

In [1]:
import numpy as np
inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
output = np.maximum(0, inputs)
print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [2]:
# ReLU activation class
class ReLUActivation:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

ReLU can be used in forward layers, but for output we want something that gives probabilities.
This is best done by Softmax.

In [14]:
# Let's say we get the inputs as follows from neural network for 3 batches and 3 features
inputs = [[1, 2.5, 1.0], [2.0, 3.0, 2.0], [-1.5, 2.7, 3.0]]

# unnormalized probabilities
exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))

# normalized probabilities
probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)

print(probabilities)

np.sum(probabilities, axis=1)

[[0.15428077 0.69143845 0.15428077]
 [0.21194156 0.57611688 0.21194156]
 [0.00634101 0.42285902 0.57079997]]


array([1., 1., 1.])

Softmax activation class

In [15]:
class SoftmaxActivation:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

<h3>Let's check with spiral data</h3>

In [17]:
from nnfs.datasets import spiral_data

In [16]:
class DenseLayer:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [20]:
X, y = spiral_data(samples=100, classes=3)

dense1 = DenseLayer(2, 3)
activation1 = ReLUActivation()

dense2 = DenseLayer(3, 3)
activation2 = SoftmaxActivation()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333333 0.33333333 0.33333333]
 [0.33333331 0.33333336 0.33333333]
 [0.33333298 0.33333378 0.33333324]
 [0.33333267 0.33333417 0.33333316]
 [0.3333333  0.33333338 0.33333332]]
