In [2]:
# neuron with 3 inputs and 1 output
import numpy as np

inputs = [0.5, 0.2, 0.1]
weights = [0.4, 0.3, 0.9]
bias = 2
output = np.dot(weights, inputs) + bias
print(output)

2.35


In [9]:
# layer of neurons
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]
layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

[4.8   1.21  2.385]


In [ ]:
# batch of inputs
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

# we cannot transpose list in python so convert it to numpy array
layer_outputs = np.dot(inputs, np.array(weights).T) + biases
print(layer_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
